### ISSUE TITLE
Error while executing ffmpeg when no audio stream is present

### ISSUE THREAD

**Issue by reopru** [sverrirs/mp4box-catgen#1]
When combining several files with no audio (only video stream) this error occur:

`Stream specifier ':a' in filtergraph description [0:v]scale=1024:576:force_original_aspect_ratio=1[v0];[1:v]scale=1024:576:force_original_aspect_ratio=1[v1];[v0][0:a][v1][1:a]concat=n=2:v=1:a=1[v][a]
matches no streams.`

[error.log](https://github.com/sverrirs/mp4combine/files/2183206/error.log) attached.

**Comment by sverrirs** [comment]
Hi and thanks for taking my tool for a spin.

I didn't actually anticipate merging streams without audio. However it may be simple to add. 

Can you try executing the following altered command from a cmd prompt on your machine?

```

E:\V\mp4combine-master\bin\ff\ffmpeg.exe -i W:\New\Transalpina_x264\2018_0616_125021_401.mp4 -i W:\New\Transalpina_x264\2018_0616_125321_402.mp4 -i W:\New\Transalpina_x264\2018_0616_125621_403.mp4 -i W:\New\Transalpina_x264\2018_0616_125921_404.mp4 -filter_complex [0:v]scale=1024:576:force_original_aspect_ratio=1[v0];[1:v]scale=1024:576:force_original_aspect_ratio=1[v1];[2:v]scale=1024:576:force_original_aspect_ratio=1[v2];[3:v]scale=1024:576:force_original_aspect_ratio=1[v3];[v0][v1][v2][v3]concat=n=4:v=1[v] -map [v] -hide_banner -loglevel verbose -stats -y W:\New\all_clips_silenttest.mp4
```

**Comment by reopru** [comment]
Hi and thanks for your fast and kind response. I was looking for such a tool for a months now and then I've found yours. Great work!
To the topic: Yes, the snipped works very well and concatenate all 4 files in one on my machine. This should be the solution, I guess.

**Comment by sverrirs** [comment]
There is a new switch in v2.5 `--noaudio` that disables merging of the audio channels from the source clips. This should solve your issue. Thanks for taking the time to report it. :)

**Comment by reopru** [comment]
Thanks! Work like a charm :)
