### ISSUE TITLE
Error when running combine.py

### ISSUE THREAD

**Issue by nigelhiggs** [sverrirs/mp4box-catgen#2]
Not sure what this means but windows tells me I am missing "js.dll" no idea what it is and i'm not gonna over think it just gonna find another project. I just want to leave a comment in case others stumble onto the issue.

**Comment by SmokingCrop** [comment]
I had the same issue, but was able to find the files with VoidTools' Search Everything.
Install https://www.mp4joiner.org/en/ and you'll have a program files(x86)\MP4Tools\bin folder which has js.dll , as well as ssleay.dll and libeay32.dll which are required. Add these .dll's to the src folder of this script.

However it just gives another generic error after that.. can't be bothered to search further as it doesn't have any meaning. (can't start the application (0xc000007b) ..

**Comment by sverrirs** [comment]
The script assumes that the path to mp4box is added to your system PATH variable.
This is, i believe, an option in the mp4box installer.
